---
driver:
  name: vagrant

provisioner:
  require_chef_omnibus: true
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    - recipe[encfs]
    - recipe[test::default]
